name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10.14
  - conda-forge::jupyterlab=4.1.3
  - conda-forge::seaborn=0.13.2
  - conda-forge::pandas=2.2.1
  - conda-forge::pip=23.3.1
  - conda-forge::ydata-profiling=4.10.0
  - conda-forge::pyarrow=14.0.2  
  #- hydra-core=1.3.2
  #- matplotlib=3.8.2
  #- pandas=2.1.3
  #- scikit-learn=1.3.2
  - pip:
      - wandb==0.16.4
      - ipywidgets==8.1.0
      - entrypoints==0.4
      #- mlflow==2.8.1
      
