name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10.14
  - conda-forge::pandas=2.2.1
  - conda-forge::pip=23.3.1
  - conda-forge::requests=2.24.0
  - conda-forge::scikit-learn=1.4.1
  - pip:
      - wandb==0.16.4
      #- git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
      #- mlflow==2.8.1

