name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10.14
  - conda-forge::pandas=2.2.1
  - conda-forge::pytest=8.0.2
  - conda-forge::scipy=1.12.0
  - conda-forge::pip=23.3.1
  - pip:
      - wandb==0.16.4
      #- mlflow==2.8.1
