name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::pyyaml=6.0.1
  - conda-forge::hydra-core=1.3.2
  - conda-forge::pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
