name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::hydra-core=1.3.2
  - conda-forge::matplotlib=3.8.2
  - conda-forge::pandas=2.1.3
  - conda-forge::jupyterlab=4.0.9
  - conda-forge::pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
