name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10.14
  - conda-forge::pandas=2.2.1
  - conda-forge::pip=23.3.1
  - conda-forge::pyarrow=14.0.2
  - pip:
      - wandb==0.16.4
      #- mlflow==2.8.1

